# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/configuredialog.ui'
#
# Created: Tue May 12 12:09:56 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(418, 228)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.configGroupBox = QtGui.QGroupBox(Dialog)
        self.configGroupBox.setTitle("")
        self.configGroupBox.setObjectName("configGroupBox")
        self.formLayout = QtGui.QFormLayout(self.configGroupBox)
        self.formLayout.setObjectName("formLayout")
        self.idLabel = QtGui.QLabel(self.configGroupBox)
        self.idLabel.setObjectName("idLabel")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.idLabel)
        self.idLineEdit = QtGui.QLineEdit(self.configGroupBox)
        self.idLineEdit.setObjectName("idLineEdit")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.idLineEdit)
        self.fileLocLabel = QtGui.QLabel(self.configGroupBox)
        self.fileLocLabel.setObjectName("fileLocLabel")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.fileLocLabel)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fileLocLineEdit = QtGui.QLineEdit(self.configGroupBox)
        self.fileLocLineEdit.setObjectName("fileLocLineEdit")
        self.horizontalLayout.addWidget(self.fileLocLineEdit)
        self.fileLocButton = QtGui.QPushButton(self.configGroupBox)
        self.fileLocButton.setObjectName("fileLocButton")
        self.horizontalLayout.addWidget(self.fileLocButton)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.colLabel = QtGui.QLabel(self.configGroupBox)
        self.colLabel.setObjectName("colLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.colLabel)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.colXLabel = QtGui.QLabel(self.configGroupBox)
        self.colXLabel.setObjectName("colXLabel")
        self.horizontalLayout_2.addWidget(self.colXLabel)
        self.colXSpinBox = QtGui.QSpinBox(self.configGroupBox)
        self.colXSpinBox.setObjectName("colXSpinBox")
        self.horizontalLayout_2.addWidget(self.colXSpinBox)
        self.colYLabel = QtGui.QLabel(self.configGroupBox)
        self.colYLabel.setObjectName("colYLabel")
        self.horizontalLayout_2.addWidget(self.colYLabel)
        self.colYSpinBox = QtGui.QSpinBox(self.configGroupBox)
        self.colYSpinBox.setProperty("value", 1)
        self.colYSpinBox.setObjectName("colYSpinBox")
        self.horizontalLayout_2.addWidget(self.colYSpinBox)
        self.colZLabel = QtGui.QLabel(self.configGroupBox)
        self.colZLabel.setObjectName("colZLabel")
        self.horizontalLayout_2.addWidget(self.colZLabel)
        self.colZSpinBox = QtGui.QSpinBox(self.configGroupBox)
        self.colZSpinBox.setProperty("value", 2)
        self.colZSpinBox.setObjectName("colZSpinBox")
        self.horizontalLayout_2.addWidget(self.colZSpinBox)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.gridLayout.addWidget(self.configGroupBox, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.idLineEdit, self.fileLocLineEdit)
        Dialog.setTabOrder(self.fileLocLineEdit, self.fileLocButton)
        Dialog.setTabOrder(self.fileLocButton, self.colXSpinBox)
        Dialog.setTabOrder(self.colXSpinBox, self.colYSpinBox)
        Dialog.setTabOrder(self.colYSpinBox, self.colZSpinBox)
        Dialog.setTabOrder(self.colZSpinBox, self.buttonBox)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Configure Point Source Step", None, QtGui.QApplication.UnicodeUTF8))
        self.idLabel.setText(QtGui.QApplication.translate("Dialog", "Identifier:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.fileLocLabel.setText(QtGui.QApplication.translate("Dialog", "Filename:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.fileLocButton.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.colLabel.setText(QtGui.QApplication.translate("Dialog", "Columns:", None, QtGui.QApplication.UnicodeUTF8))
        self.colXLabel.setText(QtGui.QApplication.translate("Dialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.colYLabel.setText(QtGui.QApplication.translate("Dialog", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.colZLabel.setText(QtGui.QApplication.translate("Dialog", "Z", None, QtGui.QApplication.UnicodeUTF8))

